[metadata]
  name = "rust-cross-versions-{{ $.Env.GitReference }}"

[global]
  plan = "libp2p/ping/rust"
  case = "ping"
  builder = "docker:generic"
  runner = "local:docker"
  concurrent_builds = 1

{{ with (load_resource "./rust.toml" ) }}
  {{ range .groups }}
    [[groups]]
    id = "{{ .Id }}"
    instances = { count = 1 }

    [groups.build_config.build_args]
      CARGO_FEATURES = '{{ .CargoFeatures }}'
  {{ end }}

  {{ with .master }}
    [[groups]]
    id = "master"
    instances = { count = 1 }

    [groups.build_config.build_args]
      CARGO_FEATURES = '{{ .CargoFeatures }}'
  {{ end }}

  {{ if $.Env.GitReference }}
    {{ with .custom }}
      [[groups]]
      id = "custom"
      instances = { count = 1 }

      [groups.build_config.build_args]
        CARGO_FEATURES = '{{ .CargoFeatures }}'
        CARGO_REMOVE = '{{ .CargoFeatures }}'
        CARGO_PATCH = """
          {{ .CargoFeatures }} = {package = "libp2p", git = "https://{{ or $.Env.GitTarget "github.com/libp2p/rust-libp2p" }}", rev = "{{ $.Env.GitReference }}", default_features = false, features = [ "websocket", "mplex", "yamux", "tcp-async-io", "ping", "noise", "dns-async-std" ], optional = true}
          """
    {{ end }}
  {{ end }}
{{ end }}
