[metadata]
  name = "rust-cross-versions {{ .Env.GitReference }}"

[global]
  plan = "libp2p/ping/rust"
  case = "ping"
  builder = "docker:generic"
  total_instances = {{ if .Env.GitReference }}5{{ else }}4{{ end }}
  runner = "local:docker"

[[groups]]
  id = "v0.44.0"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v044'

[[groups]]
  id = "v0.45.1"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v045'

[[groups]]
  id = "v0.46.0"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v046'

[[groups]]
  id = "master"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v047'


{{ if .Env.GitReference }}
[[groups]]
  # warning: patch for `libp2p` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
  # warning: Patch `libp2p v0.47.0 (https://github.com/libp2p/rust-libp2p?branch=master#d0da3a09)` was not used in the crate graph.
  id = "current"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v047'
    CARGO_REMOVE = 'libp2pv0470'
    CARGO_PATCH = """
libp2pv0470 = {package = "libp2p", git = "https://{{ or .Env.GitTarget "github.com/libp2p/rust-libp2p" }}", branch = "{{ .Env.GitReference }}", default_features = false, features = [ "websocket", "mplex", "yamux", "tcp-async-io", "ping", "noise", "dns-async-std" ], version = "0.47.0", optional = true}
"""
{{ end }}