name = "webrtc-ping"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "webrtc"
instances = { min = 1, max = 10000, default = 1 }

  [testcases.params]
  secure_channel    = { type = "enum", desc = "secure channel used", values = ["noise"], default = "noise" }
  max_latency_ms    = { type = "int", desc = "maximum value for random local link latency", unit = "ms", default = 1000 }
  iterations        = { type = "int", desc = "number of ping iterations we'll run against each peer", unit = "count", default = 2 }

