[[runs]]
Id = "rust-master x rust-v0.47.0"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x rust-v0.46.0"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x rust-v0.45.1"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x rust-v0.44.0"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-master"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.22"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.21"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.20"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.19"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.17"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-master x go-v0.11"

  [[runs.groups]]
  Id = "rust-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x rust-v0.46.0"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x rust-v0.45.1"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x rust-v0.44.0"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-master"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.22"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.21"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.20"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.19"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.17"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.47.0 x go-v0.11"

  [[runs.groups]]
  Id = "rust-v0.47.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x rust-v0.45.1"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x rust-v0.44.0"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-master"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.22"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.21"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.20"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.19"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.17"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.46.0 x go-v0.11"

  [[runs.groups]]
  Id = "rust-v0.46.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x rust-v0.44.0"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-master"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.22"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.21"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.20"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.19"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.17"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.45.1 x go-v0.11"

  [[runs.groups]]
  Id = "rust-v0.45.1"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-master"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.22"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.21"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.20"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.19"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.17"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "rust-v0.44.0 x go-v0.11"

  [[runs.groups]]
  Id = "rust-v0.44.0"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.22"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.21"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.20"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.19"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.17"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-master x go-v0.11"

  [[runs.groups]]
  Id = "go-master"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.22 x go-v0.21"

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.22 x go-v0.20"

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.22 x go-v0.19"

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.22 x go-v0.17"

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.22 x go-v0.11"

  [[runs.groups]]
  Id = "go-v0.22"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.21 x go-v0.20"

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.21 x go-v0.19"

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.21 x go-v0.17"

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.21 x go-v0.11"

  [[runs.groups]]
  Id = "go-v0.21"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.20 x go-v0.19"

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.20 x go-v0.17"

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.20 x go-v0.11"

  [[runs.groups]]
  Id = "go-v0.20"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.19 x go-v0.17"

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.19 x go-v0.11"

  [[runs.groups]]
  Id = "go-v0.19"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[runs]]
Id = "go-v0.17 x go-v0.11"

  [[runs.groups]]
  Id = "go-v0.17"

    [runs.groups.instances]
    count = 1

  [[runs.groups]]
  Id = "go-v0.11"

    [runs.groups.instances]
    count = 1

[[instances]]
Id = "rust-master"
Version = "0.48.0"
IsMaster = true
Implementation = "rust"
CargoFeatures = "libp2pmaster"

[[instances]]
Id = "rust-v0.47.0"
Implementation = "rust"
CargoFeatures = "libp2pv0470"

[[instances]]
Id = "rust-v0.46.0"
Implementation = "rust"
CargoFeatures = "libp2pv0460"

[[instances]]
Id = "rust-v0.45.1"
Implementation = "rust"
CargoFeatures = "libp2pv0450"

[[instances]]
Id = "rust-v0.44.0"
Implementation = "rust"
CargoFeatures = "libp2pv0440"

[[instances]]
Id = "go-master"
GoVersion = "1.18"
IsMaster = true
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = "v0.22"

[[instances]]
Id = "go-v0.22"
GoVersion = "1.18"
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = "v0.22"

[[instances]]
Id = "go-v0.21"
GoVersion = "1.18"
Modfile = "go.v0.21.mod"
Implementation = "go"
Selector = "v0.21"

[[instances]]
Id = "go-v0.20"
GoVersion = "1.18"
Modfile = "go.v0.20.mod"
Implementation = "go"
Selector = "v0.20"

[[instances]]
Id = "go-v0.19"
GoVersion = "1.17"
Modfile = "go.v0.19.mod"
Implementation = "go"
Selector = "v0.19"

[[instances]]
Id = "go-v0.17"
GoVersion = "1.16"
Modfile = "go.v0.17.mod"
Implementation = "go"
Selector = "v0.17"

[[instances]]
Id = "go-v0.11"
GoVersion = "1.14"
Modfile = "go.v0.11.mod"
Implementation = "go"
Selector = "v0.11"
