[master]
Id = "go-master"
GoVersion = '1.18'
IsMaster = true
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = 'v0.22'
SupportedTransports = ["tcp", "quic"]

# [custom]
# Id = "go-custom"
# GoVersion = '1.18'
# IsCustom = true
# Modfile = "go.v0.22.mod"
# Implementation = "go"
# Selector = 'v0.22'
# SupportedTransports = ["tcp", "quic"]

[[groups]]
Id = "go-v0.22"
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = 'v0.22'
SupportedTransports = ["tcp", "quic"]

[[groups]]
Id = "go-ckousik"
GoVersion = '1.18'
Modfile = "go.ckousik.mod"
Implementation = "go"
Repository = 'https://github.com/ckousik/go-libp2p.git'
Branch = 'ckousik/webrtc'
Selector = 'ckousik'
SupportedTransports = ["tcp", "quic", "webrtc"]

# [[groups]]
# Id = "go-v0.21"
# GoVersion = '1.18'
# Modfile = "go.v0.21.mod"
# Implementation = "go"
# Selector = 'v0.21'
# SupportedTransports = ["tcp", "quic"]

# [[groups]]
# Id = "go-v0.20"
# GoVersion = '1.18'
# Modfile = "go.v0.20.mod"
# Implementation = "go"
# Selector = 'v0.20'
# SupportedTransports = ["tcp", "quic"]
#
# [[groups]]
# Id = "go-v0.19"
# GoVersion = '1.17'
# Modfile = "go.v0.19.mod"
# Implementation = "go"
# Selector = 'v0.19'
# SupportedTransports = ["tcp", "quic"]
#
#
# [[groups]]
# Id = "go-v0.17"
# GoVersion = '1.16'
# Modfile = "go.v0.17.mod"
# Implementation = "go"
# Selector = 'v0.17'
# SupportedTransports = ["tcp", "quic"]
#
# [[groups]]
# Id = "go-v0.11"
# GoVersion = '1.14'
# Modfile = "go.v0.11.mod"
# Implementation = "go"
# Selector = 'v0.11'
# SupportedTransports = ["tcp", "quic"]
