on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

name: libp2p simple webrtc test

jobs:
  run-multidim-interop:
    runs-on: ["self-hosted", "linux", "x64", "4xlarge"] # https://github.com/pl-strflt/tf-aws-gh-runner/blob/main/runners.tf
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/simple-webrtc-test
        with:
          s3-cache-bucket: libp2p-by-tf-aws-bootstrap
          s3-access-key-id: ${{ vars.S3_AWS_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          worker-count: 16
  build-without-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Purposely not using secrets to replicate how forks will behave.
      - uses: ./.github/actions/simple-webrtc-test
        with:
          # It's okay to not run the tests, we only care to check if the tests build without cache.
          test-filter: '"no test matches this, skip all"'
