on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

name: libp2p multidimensional interop test

jobs:
  run-multidim-interop:
    uses: "./.github/workflows/run-testplans.yml"
    with:
      dir: "multidim-interop"
    secrets: inherit
  run-multidim-interop-ng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-interop-ping-test
