on:
  workflow_dispatch:
    inputs:
      testground_endpoint:
        type: string
        required: false
        description: testground endpoint
      custom_git_reference:
        type: string
        required: false
        description: rust ref
      custom_git_target:
        type: string
        required: false
        description: repository to use as replace target
        default: github.com/libp2p/rust-libp2p

name: rust-libp2p ping - rust test with testground.

jobs:
  run-libp2p-test-plans:
    # If you intend to use this workflow from another repo,
    # you need to pass the repo and the version:
    # uses: "libp2p/test-plans/.github/workflows/run-composition.yml@master"
    uses: "./.github/workflows/run-composition.yml"
    with:
      composition_file: "ping/_compositions/rust-cross-versions.toml"
      custom_git_target: ${{ github.event.inputs.custom_git_target }} # nothing or "some-fork/go-libp2p"
      custom_git_reference: ${{ github.event.inputs.custom_git_reference }} # a git reference
      testground_endpoint: ${{ github.event.inputs.testground_endpoint }}
